//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class ClearBehaviorFaultRequest : Message
    {
        public const string k_RosMessageName = "spot_msgs/ClearBehaviorFault";
        public override string RosMessageName => k_RosMessageName;

        public uint id;

        public ClearBehaviorFaultRequest()
        {
            this.id = 0;
        }

        public ClearBehaviorFaultRequest(uint id)
        {
            this.id = id;
        }

        public static ClearBehaviorFaultRequest Deserialize(MessageDeserializer deserializer) => new ClearBehaviorFaultRequest(deserializer);

        private ClearBehaviorFaultRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "ClearBehaviorFaultRequest: " +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
