//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class SetLocomotionRequest : Message
    {
        public const string k_RosMessageName = "spot_msgs/SetLocomotion";
        public override string RosMessageName => k_RosMessageName;

        public uint locomotion_mode;
        //  See https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference.html?highlight=mobilityparams#locomotionhint for details

        public SetLocomotionRequest()
        {
            this.locomotion_mode = 0;
        }

        public SetLocomotionRequest(uint locomotion_mode)
        {
            this.locomotion_mode = locomotion_mode;
        }

        public static SetLocomotionRequest Deserialize(MessageDeserializer deserializer) => new SetLocomotionRequest(deserializer);

        private SetLocomotionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.locomotion_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.locomotion_mode);
        }

        public override string ToString()
        {
            return "SetLocomotionRequest: " +
            "\nlocomotion_mode: " + locomotion_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
