//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class NavigateToGoal : Message
    {
        public const string k_RosMessageName = "spot_msgs/NavigateTo";
        public override string RosMessageName => k_RosMessageName;

        public string upload_path;
        //  Absolute path to map_directory, which is downloaded from tablet controller
        public string navigate_to;
        //  Waypoint id string for where to go
        public bool initial_localization_fiducial;
        //  Tells the initializer whether to use fiducials
        public string initial_localization_waypoint;
        //  Waypoint id to trigger localization 

        public NavigateToGoal()
        {
            this.upload_path = "";
            this.navigate_to = "";
            this.initial_localization_fiducial = false;
            this.initial_localization_waypoint = "";
        }

        public NavigateToGoal(string upload_path, string navigate_to, bool initial_localization_fiducial, string initial_localization_waypoint)
        {
            this.upload_path = upload_path;
            this.navigate_to = navigate_to;
            this.initial_localization_fiducial = initial_localization_fiducial;
            this.initial_localization_waypoint = initial_localization_waypoint;
        }

        public static NavigateToGoal Deserialize(MessageDeserializer deserializer) => new NavigateToGoal(deserializer);

        private NavigateToGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.upload_path);
            deserializer.Read(out this.navigate_to);
            deserializer.Read(out this.initial_localization_fiducial);
            deserializer.Read(out this.initial_localization_waypoint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.upload_path);
            serializer.Write(this.navigate_to);
            serializer.Write(this.initial_localization_fiducial);
            serializer.Write(this.initial_localization_waypoint);
        }

        public override string ToString()
        {
            return "NavigateToGoal: " +
            "\nupload_path: " + upload_path.ToString() +
            "\nnavigate_to: " + navigate_to.ToString() +
            "\ninitial_localization_fiducial: " + initial_localization_fiducial.ToString() +
            "\ninitial_localization_waypoint: " + initial_localization_waypoint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
