//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class NavigateToFeedback : Message
    {
        public const string k_RosMessageName = "spot_msgs/NavigateTo";
        public override string RosMessageName => k_RosMessageName;

        public string waypoint_id;

        public NavigateToFeedback()
        {
            this.waypoint_id = "";
        }

        public NavigateToFeedback(string waypoint_id)
        {
            this.waypoint_id = waypoint_id;
        }

        public static NavigateToFeedback Deserialize(MessageDeserializer deserializer) => new NavigateToFeedback(deserializer);

        private NavigateToFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.waypoint_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.waypoint_id);
        }

        public override string ToString()
        {
            return "NavigateToFeedback: " +
            "\nwaypoint_id: " + waypoint_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
