//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class BatteryStateArrayMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/BatteryStateArray";
        public override string RosMessageName => k_RosMessageName;

        public BatteryStateMsg[] battery_states;

        public BatteryStateArrayMsg()
        {
            this.battery_states = new BatteryStateMsg[0];
        }

        public BatteryStateArrayMsg(BatteryStateMsg[] battery_states)
        {
            this.battery_states = battery_states;
        }

        public static BatteryStateArrayMsg Deserialize(MessageDeserializer deserializer) => new BatteryStateArrayMsg(deserializer);

        private BatteryStateArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.battery_states, BatteryStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.battery_states);
            serializer.Write(this.battery_states);
        }

        public override string ToString()
        {
            return "BatteryStateArrayMsg: " +
            "\nbattery_states: " + System.String.Join(", ", battery_states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
