//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class BehaviorFaultStateMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/BehaviorFaultState";
        public override string RosMessageName => k_RosMessageName;

        public BehaviorFaultMsg[] faults;

        public BehaviorFaultStateMsg()
        {
            this.faults = new BehaviorFaultMsg[0];
        }

        public BehaviorFaultStateMsg(BehaviorFaultMsg[] faults)
        {
            this.faults = faults;
        }

        public static BehaviorFaultStateMsg Deserialize(MessageDeserializer deserializer) => new BehaviorFaultStateMsg(deserializer);

        private BehaviorFaultStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.faults, BehaviorFaultMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.faults);
            serializer.Write(this.faults);
        }

        public override string ToString()
        {
            return "BehaviorFaultStateMsg: " +
            "\nfaults: " + System.String.Join(", ", faults.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
