//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class BehaviorFaultMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/BehaviorFault";
        public override string RosMessageName => k_RosMessageName;

        //  Cause
        public const byte CAUSE_UNKNOWN = 0;
        public const byte CAUSE_FALL = 1;
        public const byte CAUSE_HARDWARE = 2;
        //  Status
        public const byte STATUS_UNKNOWN = 0;
        public const byte STATUS_CLEARABLE = 1;
        public const byte STATUS_UNCLEARABLE = 2;
        public HeaderMsg header;
        public uint behavior_fault_id;
        public byte cause;
        public byte status;

        public BehaviorFaultMsg()
        {
            this.header = new HeaderMsg();
            this.behavior_fault_id = 0;
            this.cause = 0;
            this.status = 0;
        }

        public BehaviorFaultMsg(HeaderMsg header, uint behavior_fault_id, byte cause, byte status)
        {
            this.header = header;
            this.behavior_fault_id = behavior_fault_id;
            this.cause = cause;
            this.status = status;
        }

        public static BehaviorFaultMsg Deserialize(MessageDeserializer deserializer) => new BehaviorFaultMsg(deserializer);

        private BehaviorFaultMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.behavior_fault_id);
            deserializer.Read(out this.cause);
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.behavior_fault_id);
            serializer.Write(this.cause);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "BehaviorFaultMsg: " +
            "\nheader: " + header.ToString() +
            "\nbehavior_fault_id: " + behavior_fault_id.ToString() +
            "\ncause: " + cause.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
