//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class EStopStateMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/EStopState";
        public override string RosMessageName => k_RosMessageName;

        //  Type
        public const byte TYPE_UNKNOWN = 0;
        public const byte TYPE_HARDWARE = 1;
        public const byte TYPE_SOFTWARE = 2;
        //  State
        public const byte STATE_UNKNOWN = 0;
        public const byte STATE_ESTOPPED = 1;
        public const byte STATE_NOT_ESTOPPED = 2;
        public HeaderMsg header;
        public string name;
        public byte type;
        public byte state;
        public string state_description;

        public EStopStateMsg()
        {
            this.header = new HeaderMsg();
            this.name = "";
            this.type = 0;
            this.state = 0;
            this.state_description = "";
        }

        public EStopStateMsg(HeaderMsg header, string name, byte type, byte state, string state_description)
        {
            this.header = header;
            this.name = name;
            this.type = type;
            this.state = state;
            this.state_description = state_description;
        }

        public static EStopStateMsg Deserialize(MessageDeserializer deserializer) => new EStopStateMsg(deserializer);

        private EStopStateMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.name);
            deserializer.Read(out this.type);
            deserializer.Read(out this.state);
            deserializer.Read(out this.state_description);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.name);
            serializer.Write(this.type);
            serializer.Write(this.state);
            serializer.Write(this.state_description);
        }

        public override string ToString()
        {
            return "EStopStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nname: " + name.ToString() +
            "\ntype: " + type.ToString() +
            "\nstate: " + state.ToString() +
            "\nstate_description: " + state_description.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
