//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class LeaseResourceMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/LeaseResource";
        public override string RosMessageName => k_RosMessageName;

        public string resource;
        public LeaseMsg lease;
        public LeaseOwnerMsg lease_owner;

        public LeaseResourceMsg()
        {
            this.resource = "";
            this.lease = new LeaseMsg();
            this.lease_owner = new LeaseOwnerMsg();
        }

        public LeaseResourceMsg(string resource, LeaseMsg lease, LeaseOwnerMsg lease_owner)
        {
            this.resource = resource;
            this.lease = lease;
            this.lease_owner = lease_owner;
        }

        public static LeaseResourceMsg Deserialize(MessageDeserializer deserializer) => new LeaseResourceMsg(deserializer);

        private LeaseResourceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.resource);
            this.lease = LeaseMsg.Deserialize(deserializer);
            this.lease_owner = LeaseOwnerMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.resource);
            serializer.Write(this.lease);
            serializer.Write(this.lease_owner);
        }

        public override string ToString()
        {
            return "LeaseResourceMsg: " +
            "\nresource: " + resource.ToString() +
            "\nlease: " + lease.ToString() +
            "\nlease_owner: " + lease_owner.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
