//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class LeaseArrayMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/LeaseArray";
        public override string RosMessageName => k_RosMessageName;

        public LeaseResourceMsg[] resources;

        public LeaseArrayMsg()
        {
            this.resources = new LeaseResourceMsg[0];
        }

        public LeaseArrayMsg(LeaseResourceMsg[] resources)
        {
            this.resources = resources;
        }

        public static LeaseArrayMsg Deserialize(MessageDeserializer deserializer) => new LeaseArrayMsg(deserializer);

        private LeaseArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.resources, LeaseResourceMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.resources);
            serializer.Write(this.resources);
        }

        public override string ToString()
        {
            return "LeaseArrayMsg: " +
            "\nresources: " + System.String.Join(", ", resources.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
