//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class MobilityParamsMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/MobilityParams";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg body_control;
        public uint locomotion_hint;
        public bool stair_hint;

        public MobilityParamsMsg()
        {
            this.body_control = new Geometry.PoseMsg();
            this.locomotion_hint = 0;
            this.stair_hint = false;
        }

        public MobilityParamsMsg(Geometry.PoseMsg body_control, uint locomotion_hint, bool stair_hint)
        {
            this.body_control = body_control;
            this.locomotion_hint = locomotion_hint;
            this.stair_hint = stair_hint;
        }

        public static MobilityParamsMsg Deserialize(MessageDeserializer deserializer) => new MobilityParamsMsg(deserializer);

        private MobilityParamsMsg(MessageDeserializer deserializer)
        {
            this.body_control = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.locomotion_hint);
            deserializer.Read(out this.stair_hint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.body_control);
            serializer.Write(this.locomotion_hint);
            serializer.Write(this.stair_hint);
        }

        public override string ToString()
        {
            return "MobilityParamsMsg: " +
            "\nbody_control: " + body_control.ToString() +
            "\nlocomotion_hint: " + locomotion_hint.ToString() +
            "\nstair_hint: " + stair_hint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
