//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class SystemFaultMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/SystemFault";
        public override string RosMessageName => k_RosMessageName;

        //  Severity
        public const byte SEVERITY_UNKNOWN = 0;
        public const byte SEVERITY_INFO = 1;
        public const byte SEVERITY_WARN = 2;
        public const byte SEVERITY_CRITICAL = 3;
        public HeaderMsg header;
        public string name;
        public DurationMsg duration;
        public int code;
        public ulong uid;
        public string error_message;
        public string[] attributes;
        public byte severity;

        public SystemFaultMsg()
        {
            this.header = new HeaderMsg();
            this.name = "";
            this.duration = new DurationMsg();
            this.code = 0;
            this.uid = 0;
            this.error_message = "";
            this.attributes = new string[0];
            this.severity = 0;
        }

        public SystemFaultMsg(HeaderMsg header, string name, DurationMsg duration, int code, ulong uid, string error_message, string[] attributes, byte severity)
        {
            this.header = header;
            this.name = name;
            this.duration = duration;
            this.code = code;
            this.uid = uid;
            this.error_message = error_message;
            this.attributes = attributes;
            this.severity = severity;
        }

        public static SystemFaultMsg Deserialize(MessageDeserializer deserializer) => new SystemFaultMsg(deserializer);

        private SystemFaultMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.name);
            this.duration = DurationMsg.Deserialize(deserializer);
            deserializer.Read(out this.code);
            deserializer.Read(out this.uid);
            deserializer.Read(out this.error_message);
            deserializer.Read(out this.attributes, deserializer.ReadLength());
            deserializer.Read(out this.severity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.name);
            serializer.Write(this.duration);
            serializer.Write(this.code);
            serializer.Write(this.uid);
            serializer.Write(this.error_message);
            serializer.WriteLength(this.attributes);
            serializer.Write(this.attributes);
            serializer.Write(this.severity);
        }

        public override string ToString()
        {
            return "SystemFaultMsg: " +
            "\nheader: " + header.ToString() +
            "\nname: " + name.ToString() +
            "\nduration: " + duration.ToString() +
            "\ncode: " + code.ToString() +
            "\nuid: " + uid.ToString() +
            "\nerror_message: " + error_message.ToString() +
            "\nattributes: " + System.String.Join(", ", attributes.ToList()) +
            "\nseverity: " + severity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
