//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Spot
{
    [Serializable]
    public class WiFiStateMsg : Message
    {
        public const string k_RosMessageName = "spot_msgs/WiFiState";
        public override string RosMessageName => k_RosMessageName;

        //  Mode
        public const byte MODE_UNKNOWN = 0;
        public const byte MODE_ACCESS_POINT = 1;
        public const byte MODE_CLIENT = 2;
        public byte current_mode;
        public string essid;

        public WiFiStateMsg()
        {
            this.current_mode = 0;
            this.essid = "";
        }

        public WiFiStateMsg(byte current_mode, string essid)
        {
            this.current_mode = current_mode;
            this.essid = essid;
        }

        public static WiFiStateMsg Deserialize(MessageDeserializer deserializer) => new WiFiStateMsg(deserializer);

        private WiFiStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_mode);
            deserializer.Read(out this.essid);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_mode);
            serializer.Write(this.essid);
        }

        public override string ToString()
        {
            return "WiFiStateMsg: " +
            "\ncurrent_mode: " + current_mode.ToString() +
            "\nessid: " + essid.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
